### ISSUE TITLE
字体命名问题

### ISSUE THREAD

**Issue by NightFurySL2001** [Pal3love/Source-Han-TrueType#10]
根据思源的[授权信息](https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt)，Source 及 “思源” 两个词汇是保留字型名称，后期的衍生版本不可使用 Source 及 “思源” 作为字体名称。

**Comment by Pal3love** [comment]
这个版本并不是再创作，没有改动任何设计和字体本身的内容。
如果仍有疑问，欢迎重开此问题并继续讨论。非常感谢指出这一点！

**Comment by NightFurySL2001** [comment]
根据 OFL 原文：

> "Modified Version" refers to any derivative made by adding to,
deleting, or substituting -- in part or in whole -- any of the
components of the Original Version, by **changing formats** or by porting
the Font Software to a new environment.
“修改版本” (modified version) 指通过增加、删除或替换 (substituting) “原始版本”中的任何部分或整体构件、**转换字型软件的格式**或移植字型软件到新的运作环境中而产生的衍生版本。

本字体属于转换格式 (changing formats)，意属本字体属于衍生版本（Modified Version）。因此，下面的授权仍旧起效：

> 3) **No Modified Version of the Font Software may use the Reserved Font
Name(s)** unless explicit written permission is granted by the
corresponding Copyright Holder. This restriction only applies to the
primary font name as presented to the users.
**“修改版本”的“字型软件”不得使用“保留字型名称”**，除非相应名称的版权持有者授予明确的书面同意许可。此项限制仅适用于对用户显示的主要字型名称 (primary font name)。

**Comment by Pal3love** [comment]
感谢 deep dive on this issue！我会在随后的版本中考虑更换名称。

**Comment by NightFurySL2001** [comment]
请将本issue重新开启，因为您仍旧违反了思源的 SIL OFL 授权，有必要让使用者知道。您的 License 文件内没有附上原字体的版权标记 （Copyright declaration），可视为盗取了思源的成果而未标记来源。

**Comment by Pal3love** [comment]
感谢指出，我昨天已经将字体文件从 repo 中完全删除，包括所有 commit history，现在这个 repo 只留下了脚本和文档，供感兴趣的用户自己转换。我会随后在发行版中也将文件删除。也请您在 GitHub 上搜索其他的思源 ttf repo，帮这些 repo 的作者一起规避该法律风险。谢谢！

**Comment by Pal3love** [comment]
Reopen the issue to address your concern.

感谢您的跟进哈。我在这里有三点想跟您探讨：

1. 我刚才 review 了一下思源黑体和思源宋体的官方 repo，其实他们有不少关于 ttf 版本的 issues，我在这里引用一下：

**Source Han Sans**
[Gridfit](https://github.com/adobe-fonts/source-han-sans/issues/3)
[Is there any chance to release TTF version ?](https://github.com/adobe-fonts/source-han-sans/issues/15)
[TrueType (TTF)](https://github.com/adobe-fonts/source-han-sans/issues/263)

**Source Han Serif**
[How To Use It In AutoCAD](https://github.com/adobe-fonts/source-han-serif/issues/69)
[Could you support TTF font?](https://github.com/adobe-fonts/source-han-serif/issues/82)

从这些 issues 中可以看到，官方是**事实上（de facto）支持和鼓励**第三方的（不更名）ttf 转换和 GitHub 等其他平台的发布的。GitHub 和其他平台也因此长期存在大量第三方思源 ttf。既然第三方 ttf 受到官方事实上的支持，那本 repo 发布的 ttf 字体也应该和那些包括 GitHub repos 在内的其他 ttf 版本一样，享有同等待遇。

2. 我无法苟同您观点中的“盗取”一词，因为在这个 repo 发布的 ttf 字体文件中，所有字段清楚标明了 Adobe 作为作者和版权方的地位。我没有修改任何字段（包括 `name` 表、`OS/2` 表等），更没有给 Source 这个 reserved name 署上我自己的名字。此外，思源项目作为 Adobe 和各厂商数年的劳动成果，按照您的推论，给字体换个名字（和改动设计）之后，以新作者署名重新发布，就不算“盗取思源成果”了吗？

3. 我的 License 文件是直接从[思源宋体官方 repo](https://github.com/adobe-fonts/source-han-serif/blob/master/LICENSE.txt) 复制过来的，我不清楚您为什么说我没有附上原字体的版权标记。

谢谢！

**Comment by NightFurySL2001** [comment]
1. 官方允许/鼓励ttf发布，但是对命名问题并未表态，仅推荐其他人使用相关repo提供的代码自行制作而已（https://github.com/adobe-fonts/source-han-sans/issues/15#issuecomment-49298697 、 https://github.com/adobe-fonts/source-han-serif/issues/69#issuecomment-332852779 、 https://github.com/adobe-fonts/source-han-serif/issues/82#issuecomment-567161775 ）。相关issue已经在 https://github.com/be5invis/source-han-sans-ttf/issues/8 和 https://github.com/junmer/source-han-serif-ttf/issues/3 提出。

2, 3. 如若造成您的困扰，我非常抱歉。该详细是从思源黑体官方repo的授权文件（ https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt ）、思源黑体 Mono 官方repo的授权文件（ https://github.com/adobe-fonts/source-han-mono/blob/master/LICENSE.md ）下提出（参见本issue第一个comment的链接已有提及），未注意思源宋体官方repo没有相关解说。下附思源黑体官方repo的版权解说（应当附在SIL OFL的文件开始）：
```
Copyright 2014-2021 Adobe (http://www.adobe.com/), with Reserved Font
Name 'Source'. Source is a trademark of Adobe in the United States
and/or other countries.
```
我也撤回关于“可视为盗取了思源的成果而未标记来源。”的评价。相关缺失已经在 https://github.com/adobe-fonts/source-han-serif/issues/161 询问。

**Comment by Pal3love** [comment]
> 1. 官方允许/鼓励ttf发布，但是对命名问题并未表态

官方是有事实上的表态的。在上述 issues 中，不少回复引用了第三方的思源 ttf 下载：

https://github.com/adobe-fonts/source-han-sans/issues/3#issuecomment-321812944
https://github.com/adobe-fonts/source-han-sans/issues/15#issuecomment-68501723
https://github.com/adobe-fonts/source-han-sans/issues/15#issuecomment-321812434
https://github.com/adobe-fonts/source-han-serif/issues/69#issuecomment-332861837

官方既没有禁止或反对这些回复，也没有要求这些第三方作者关闭/删除他们的发布，这已经足够清楚地表达了官方的态度，即事实上支持和鼓励第三方转换和发布思源的 ttf 版本。

Closing the issue if you don't have any other questions. Thanks to let me know!

**Comment by NightFurySL2001** [comment]
如果您觉得有必要让其他使用者使用的话，还是非常欢迎将字体文件放上来，readme内特别标注即可。当然，如果放上字体文件的话，license的最前面需要追加思源的版权信息以标记来源：
```
Copyright 2014-2021 Adobe (http://www.adobe.com/), with Reserved Font
Name 'Source'. Source is a trademark of Adobe in the United States
and/or other countries.
```

官方没有禁止或反对不代表他们支持和鼓励第三方**发表**思源ttf版本，他们仅采取了沉默处理方式。官方人员/用户（如 [davelab6](https://github.com/davelab6)、[kenlunde](https://github.com/kenlunde)、[miguelsousa](https://github.com/miguelsousa)）仅支持和鼓励第三方需要使用时**自行转换文件**而已。

OFL设置RFN的初衷就是要避免后续衍生字体以自己的名义发布声称是自己的字体，或者同名的方式混淆使用者。在散播时如果预先让使用者了解下载的衍生字体并非官方发布的文件，我个人是觉得可以保留的。参见：https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web_fonts_and_RFNs ，其中有解说关于 WOFF 转换保留RFN名称的使用方式。

**Comment by Pal3love** [comment]
感谢您的建议，我已经在 README 的醒目位置标注了非官方的字样，也在 LICENSE.txt 的开头添加了 RFN，确保使用者不会将我的 repo 与官方混淆。同样，也希望您给 GitHub 上的其他思源 ttf repo 提出建议，请作者们表明他们的 repo 并非官方版本。

您对“沉默处理”的理解，恕我无法赞同。Adobe 作为巨头有成熟的法务体系，其所有员工都经过了严格的法务培训。他们以 Adobe 员工的身份，在包括 GitHub 上的任何平台的任何言行都代表 Adobe 官方。如果 Adobe 真的对第三方思源 ttf 有许可协议上的 concern，是不存在“沉默处理”这种模棱两可的做法的。我提到的 issues 和回复都已经公开存在 5-8 年了，这些 issues 甚至都早已被 Adobe 官方关闭（存档）。Adobe 在这么长的时间内对发生在自己官方 repo 上的 issue 内容“沉默”就是事实上的许可。
