### ISSUE TITLE
能否更新下思源黑体的版本

### ISSUE THREAD

**Issue by fatloong** [Pal3love/Source-Han-TrueType#11]
现在思源黑体版本已经更新到2.002了

**Comment by Masaiki** [comment]
https://github.com/VegeHime/Source-Han-TrueType
fork出了一个分支跟进原字体的更新。

**Comment by Pal3love** [comment]
感谢 fork 和继续跟进！我回来啦！我这边也更新到最新版本了，压缩格式换成了 ZIP，同时 Code JP 换成了完整版 Mono。欢迎下载！

**Comment by ShimotsukiH** [comment]
感谢更新，但是，下载不了。
下载器idm显示[connect error 5]
