### ISSUE TITLE
为什么没有单独的SC版本？

### ISSUE THREAD

**Issue by kidzgy** [Pal3love/Source-Han-TrueType#12]
我发现SC版只在SourceHanSans.zip里，并没有单独的SC。

**Comment by Pal3love** [comment]
SC、TC、HC、J、K 五种语言都封装在了同一个 ttc 文件里，因为他们共享同样的字形库。所以只需安装一个 ttc 文件，字体菜单就会同时出现五种语言的字体。思源黑体/宋体的原版 otc 也是这么设计的，65535 个字形其实是简繁港日韩的并集，而并非每个语言都做了这么多字。因此，单独为每个语言设立 ttf 会产生大量重复数据，非常占用磁盘空间（现在的 ttc 体积 x 5）。如果真的只需要国标字形的话，您可以试一试`SourceHanSansCN.zip`，这里面的 ttf 是国标子集，只包含国标字形。

**Comment by wohenbushuang** [comment]
@Pal3love 感谢维护，不过还是能希望有SC版本的TTF，有几点原因希望参考：

1. > 按照官方说明，CN版本字体应该是不全

#2 提到，CN字体不全。虽然用的时候很难遇上，不过怪难受的

2. mono 等宽字体官方只有语言子集，可以三个字体统一都给出语言子集

3. > SC、TC、HC、J、K 五种语言都封装在了同一个 ttc 文件里，因为他们共享同样的字形库。所以只需安装一个 ttc 文件，字体菜单就会同时出现五种语言的字体

ttf文件最为基础，各种调用方法的支持也最为完善，ttc有的程序不支持，这也是我们来找ttf的原因

4. > 单独为每个语言设立 ttf 会产生大量重复数据，非常占用磁盘空间（现在的 ttc 体积 x 5）

担心产生大量重复数据的话，可以先给个SC，其他子集有人需要的话再开issue？

**Comment by Pal3love** [comment]
CN 仅仅去掉了日韩港台地区的同码异体字而已，这些异体字在大陆环境里用不到，不会出现不全的情况。譬如“空”字，简体规范的第五画是点，但日本规范是捺。这就是一个同码异体字，即同样的编码，不同的写法。65535 的“完整版”思源同时包含这两种写法，CN 只是去掉了日本版写法而已，在使用中并不会缺字（“空”的大陆写法依然存在）。希望这个例子能帮你理解思源不同地区版本的差异。

如果一定需要 65535 字的 ttf 格式的话，用 Adobe 的 AFDKO 就能快速从 ttc 文件解包。

- 首先确保电脑安装了 Python 3 和 `pip`，运行这个命令安装 AFDKO：

```
pip install afdko
```

- 然后就可以用 AFDKO 附带的 `otc2otf` 工具从 ttc 解包 ttf 啦：

```
otc2otf 某个ttc字体文件.ttc
```

再次说明，生成的 5 个 ttf 文件内容几乎完全相同，唯一的区别是编码映射（`cmap`表）分别对应各地区的同码异体字而已。
