### ISSUE TITLE
Source Han Sans updated to 2.000

### ISSUE THREAD

**Issue by kidonng** [Pal3love/Source-Han-TrueType#3]
We need TrueType version updated as well!
https://github.com/adobe-fonts/source-han-sans/releases/tag/2.000R

**Comment by Pal3love** [comment]
I'll do it ASAP. Thank you so much for mentioning that!

**Comment by Pal3love** [comment]
Now I reopen this issue. This issue will remain open until SHS 2.000 is synced.

**[UPDATE on 2019-01-09]**
Since SHS 2.000 is synced, this issue is closed.

**Comment by lychichem** [comment]
So SHS has been updated to 2.002 (https://github.com/adobe-fonts/source-han-sans/tree/release) now... Will this project be updated then? @Pal3love

**Comment by Pal3love** [comment]
Updated to the latest =)
