### ISSUE TITLE
希望更新2.0版本

### ISSUE THREAD

**Issue by ShimotsukiH** [Pal3love/Source-Han-TrueType#4]
https://github.com/adobe-fonts/source-han-serif
https://github.com/adobe-fonts/source-han-sans

**Comment by kidonng** [comment]
Duplicate of #3.
Please wait for the maintainer.

**Comment by Pal3love** [comment]
最近加班太忙，我会尽快更新。非常感谢对这个 repo 的关注！

**Comment by Pal3love** [comment]
我回来啦，已更新 XD
