### ISSUE TITLE
建议使用各操作系统原生支持的压缩文件格式

### ISSUE THREAD

**Issue by shaunthegeek** [Pal3love/Source-Han-TrueType#5]
rar是商业格式，出现在开源项目里不合适；7z是开源格式，但各个编程语言支持不佳。

建议使用各操作系统原生支持的压缩文件格式，比如zip、gz、bz2，代码里下载解压也更方便。

**Comment by Pal3love** [comment]
非常感谢您的建议！rar 会在未来的更新中被逐步替换掉。

**Comment by Pal3love** [comment]
这次的更新已经全部换成 zip 格式啦，保证了全平台兼容性。欢迎下载！
