### ISSUE TITLE
咨询一下ttc包里面各字体代表的语言

### ISSUE THREAD

**Issue by geniusyjiang** [Pal3love/Source-Han-TrueType#6]
按我的理解，字体名为“思源黑体”的是官方命名的SC版，“Source Han Sans TC”的是台湾版，“Source Han Sans HC”是香港版，“Source Han Sans K”是韩国版，“Source Han Sans”就是日本版了，不知道对不对？单独打包的CN版其实也就是原版的SC版？

**Comment by Pal3love** [comment]
您好，各缩写代表的含义在官方的文件里有说明：[Source Han Sans](https://github.com/adobe-fonts/source-han-sans/tree/release)
单独打包的 CN 版是区域子集（Region-specific Subset）的简体中文版。
