### ISSUE TITLE
关于思源字体的竖排字号问题和高基线问题

### ISSUE THREAD

**Issue by Seekladoom** [Pal3love/Source-Han-TrueType#8]
大大可以试试把TTF版本的思源字体在同字号下竖排字幕变小以及高基线的问题处理一下吗？这样应该更适合一般人使用：

具体可以参考下面这两个链接：
genyo-font（源樣明體）
https://github.com/ButTaiwan/genyo-font

使用思源字体在Aegisub中制作字幕时的一些常见问题
http://bbs.vcb-s.com/forum.php?mod=viewthread&tid=3805

如有冒犯还请多多包涵。

**Comment by Pal3love** [comment]
非常感谢您的问题！这个 repo 的理念是原汁原味保留原版的思源字体，仅仅增加 TrueType 格式作为补充，并不改动任何设计方面的内容。这样，思源用户可以无需考虑、直接安装这里的文件作为 TrueType 格式替换使用，而不用担心原本设计受到任何影响。如果改动任何设计的话，这个版本就不再跟官方版同步了，同时也会引入法律上的问题。
